#cloud-config

ssh_pwauth: false

users:
  - default
  - name: nodejs
    shell: /bin/bash
    lock_passwd: true

# Vultr Rocky Linux 10 x64 provisions 3GB by default

yum_repos:
  caddy-stable:
    # See https://copr.fedorainfracloud.org/coprs/g/caddy/caddy
    name: caddy-stable
    baseurl: https://download.copr.fedorainfracloud.org/results/@caddy/caddy/epel-10-$basearch/
    enabled: true
    type: rpm-md
    gpgcheck: true
    gpgkey: https://download.copr.fedorainfracloud.org/results/@caddy/caddy/pubkey.gpg

  tailscale-stable:
    # See https://tailscale.com/docs/install/rhel/rhel-10
    name: tailscale-stable
    baseurl: https://pkgs.tailscale.com/stable/rhel/10/$basearch
    enabled: true
    type: rpm
    repo_gpgcheck: true
    gpgcheck: true
    gpgkey: https://pkgs.tailscale.com/stable/rhel/10/repo.gpg

package_update: true
package_upgrade: true
package_reboot_if_required: true

packages:
  - caddy
  - dnf-automatic
  - dnf-plugins-core
  - micro
  - sysstat
  - tailscale

write_files:
  - path: /home/nodejs/.noderc
    # See https://github.com/Schniz/fnm/issues/1119
    # See https://github.com/Schniz/fnm/issues/1315
    content: |
      # fnm
      FNM_PATH="/home/nodejs/.local/share/fnm"
      if [ -d "$FNM_PATH" ]; then
        export PATH="$FNM_PATH:$PATH"
        export XDG_RUNTIME_DIR="/tmp/run/user/$(id -u)"
        eval "$(fnm env --use-on-cd)"
      fi

      # pnpm
      export PNPM_HOME="/home/nodejs/.local/share/pnpm"
      case ":$PATH:" in
        *":$PNPM_HOME:"*) ;;
        *) export PATH="$PNPM_HOME:$PATH" ;;
      esac

  - path: /home/nodejs/.bashrc
    append: true
    content: |

      source ~/.noderc

  - path: /home/nodejs/.bash_profile
    content: |
      if [ -f ~/.bashrc ]; then
        source ~/.bashrc
      fi

  - path: /home/nodejs/init.sh
    permissions: '0755'
    content: |
      #!/bin/bash
      set -e

      curl -fsSL https://fnm.vercel.app/install | bash -s -- --skip-shell
      source ~/.noderc
      fnm install 26

      npm install -g corepack
      corepack install --global pnpm@latest
      pnpm add pm2@latest --global

      pm2 install pm2-logrotate

      rm -- "$0"

  - path: /etc/systemd/system/pm2-nodejs.service
    content: |
      [Unit]
      Description=PM2 process manager
      Documentation=https://pm2.keymetrics.io/
      After=network.target

      [Service]
      Type=forking
      User=nodejs
      LimitNOFILE=infinity
      LimitNPROC=infinity
      LimitCORE=infinity
      Environment=PM2_HOME=/home/nodejs/.pm2
      PIDFile=/home/nodejs/.pm2/pm2.pid
      Restart=on-failure

      ExecStart=/bin/bash -c 'source /home/nodejs/.noderc && pm2 resurrect'
      ExecReload=/bin/bash -c 'source /home/nodejs/.noderc && pm2 reload all'
      ExecStop=/bin/bash -c 'source /home/nodejs/.noderc && pm2 kill'

      [Install]
      WantedBy=multi-user.target

runcmd:
  # firewall
  - firewall-cmd --permanent --add-service=http --add-service=https
  - firewall-cmd --reload
  # user
  - chown -R nodejs:nodejs /home/nodejs
  - chmod 700 /home/nodejs
  - su - nodejs -c 'bash ~/init.sh'
  # services
  - systemctl enable pm2-nodejs
  - systemctl enable --now dnf-automatic-install.timer
  - systemctl enable --now sysstat sysstat-collect.timer sysstat-summary.timer
  - systemctl enable --now tailscaled
